# https://habr.com/ru/post/578744/
version: "3.8"
services:

  postgres:
    container_name: pg_container
    image: postgres:13.3
    environment:
      #POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      #- ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/dat

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "adm@in.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

#networks:
  #postgres:
    #driver: bridge