version: '3.8'

services:

 redis:
    container_name: redis
    image: "redis"
    ports:
     - 6379:6379
    volumes:
     - ./redis/data:/var/lib/redis
     - ./redis/conf:/usr/local/etc/redis/redis.conf

 celery:
    container_name: celery
    image: "celery"
    volumes:
      - ./celery:/app
    ports:
     - 5675:5675

 flower:
    container_name: flower
    image: "mher/flower"
    volumes:
      - ./flower:/app
    ports:
      - 5557:5555

 rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq
        - ./rabbitmq/log/:/var/log/rabbitmq

 redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081