# https://habr.com/ru/post/578744/

version: "3.8"
services:

  postgres_master:
    container_name: postgres_master
    hostname: postgres-master
    image: postgres
    # задаем значения необходимых переменных окружения
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5431:5432
    volumes:
      - ./postgres_master:/var/lib/postgresql/dat

  postgres_replica:
    container_name: postgres_replica
    hostname: postgres-replica
    image: postgres
    # задаем значения необходимых переменных окружения
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432
    volumes:
      - ./postgres_replica:/var/lib/postgresql/dat

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin
    # задаем значения необходимых переменных окружения
    environment:
      PGADMIN_DEFAULT_EMAIL: "adm@in.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      # пробрасываем порты (порт хоста:порт докер-контейнера)
      - 5050:80