# https://habr.com/ru/post/578744/

version: "3.8"
services:

  postgres:
    container_name: postgres
    image: postgres
    # задаем значения необходимых переменных окружения
    environment:
      #POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432
    volumes:
      #- ../2. Init Database:/docker-entrypoint-initdb.d
      # маппинг монтируемой директории на компе
      # и директории с данными приложения (смотреть на странице образа докера)
      - ./postgres:/var/lib/postgresql/dat

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin
    # задаем значения необходимых переменных окружения
    environment:
      PGADMIN_DEFAULT_EMAIL: "adm@in.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      # пробрасываем порты (порт хоста:порт докер-контейнера)
      - 5050:80